# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d14b6086106719be6f6c2baa2711076058f2c88eceb46a311d0bab2b47430c07ca7a4821f36d04c12438717c85b15a706a9e49c988aa246ce07ebe25b8977c9d

test:
  secret_key_base: cf41395bfaae1b1e6b11cb699ad0f60378edbac4d286f54b9e4bf551d5367638533aa0cd4fe6d9c904f37de24ec0a24dbd9bbffc32fa81169bb268781d38d472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
